scss_files: 'app/assets/stylesheets/**/*'

linters:
  Indentation:
    severity: warning
    width: 2
  Comment:
    enabled: false
  VendorPrefixes:
    enabled: false
  NestingDepth:
    max_depth: 5
  SelectorDepth:
    max_depth: 5
